### ISSUE TITLE
Typos in rocketswap

### ISSUE THREAD

**Issue by FlavorfulSoda** [cloakdkiller/rocketswap#49]
On popup that appears when you click withdraw rocketswap (from Tau staking)

Current:
** 10% of the yeild from all RSWP withdrawls in this contract goes to the developers of Rocketswap! It will be added automatically to the transaction total.

Suggested:
Notice: Ten percent (10%) of the yield from all RSWP withdrawals in this contract goes to the developers of Rocketswap!  This amount will be added automatically to the transaction total.

While this corrects typos and grammar a bit, I honestly don't know what this is supposed to mean.  So does this mean 10% of my yield will be _deducted_ from my transaction and given to the developers?  If so, it should not say this amount is _added_.  It could definitely use some clarification.

**Comment by JeffWScott** [comment]
Appreciate the spelling and grammar.

The 10% is enforced in the smart contract. We show you the amount you have earned in the UI minus the 10%. The subtext is there to notify you that if happen to look at the transaction it will be 10% higher than you expected.

All of that being said, this is not the way we should be doing it. I think actually just showing the total earnings and being more visible about the 10% is a better approach.

ie. 
Withdrawal 100
  minus 10% dev fee
Get 90

**Comment by cloakdkiller** [comment]
I totally agree with you here Jeff - that's a better way to do it. Issue created on the trello

**Comment by FlavorfulSoda** [comment]
Typo in "withdrawal" is still there
