### ISSUE TITLE
Minor typo

### ISSUE THREAD

**Issue by FlavorfulSoda** [cloakdkiller/rocketswap#50]
On "Pools" screen below everything it says "Wallet is not Connected".  Either "connected" should not be capitalized, or all words should be capitalized.

Also on same screen, the top text "Liquidity provider rewards" seems to be a title and would benefit from either capitalizing each first letter

**Comment by Clay99** [comment]
I found "Wallet Not Connected" it appears to have been updated to capitals already so change will be coming.  Updated "Liquidity Provider Rewards".
PR submitted.
Thanks for spotting these
